"""auth with phone number instead of email

Revision ID: 3e4a9d7b9bfc
Revises: d9ab19fe0f2d
Create Date: 2024-10-15 17:28:02.973093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e4a9d7b9bfc'
down_revision: Union[str, None] = 'd9ab19fe0f2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', sa.String(), nullable=False))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=320),
               nullable=True)
    op.drop_index('ix_user_email', table_name='user')
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=320),
               nullable=False)
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###
