name: Deployment

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS via SSH action
        uses: appleboy/ssh-action@v1.1.0
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/fastapi_jwt_boilerplate
            gh repo sync
            docker compose build server
            docker rollout -f docker-compose.yml server
            docker compose run server alembic upgrade head
