name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add remote server to known_hosts
        run: |
                    ssh-keyscan ${{ secrets.SERVER }} >> ~/.ssh/known_hosts    # Replace user@remote_server

      - name: Deploy to server
        run: |
          ssh ${{ secrets.SERVER }} << 'EOF'
            sed -i 's/^DOCKER_TAG=.*/DOCKER_TAG=${{ needs.build.outputs.date }}/' .env
            docker compose up -d
          EOF  